---
title: "base linear"
author: "PaigeT"
date: "24/11/2019"
output: html_document
---

---
title: "Churn analysis with logRegression"
author: "Paige, Vicky, and Jackie"
date: '2019-11-10'
output: 
  prettydoc::html_pretty:
  theme : cayman
  highlight : github
  math: katex
---

#This file is our basic linear regression analysis and our variable assesments


#load clean data
```{r}
library(dplyr)# Load the data
cd <- read.csv(file = "oneHotClean.csv", header = TRUE, sep = ",", 
                stringsAsFactors = T)

print("ORIGIN DATA")

summary(cd)
```

```{r}
fit <- lm(churn ~ gender + seniorcitizen + partner + dependents + tenure + phoneservice + multiplelines + onlinesecurity + onlinebackup + deviceprotection + techsupport + streamingtv + streamingmovies + paperlessbilling + monthlycharges + totalcharges, data = cd)
summary(fit)
AIC(fit)
BIC(fit)
```

```{r}
fit <- lm(churn ~ gender + seniorcitizen + partner + dependents + phoneservice + multiplelines + onlinesecurity + internetserviceDSL + internetserviceno  + onlinebackup + deviceprotection + techsupport + streamingtv + streamingmovies + contractoneyear + contracttwoyear  + paperlessbilling + paymentmethodelectroniccheck +paymentmethodmailedcheck +paymentmethodcreditcard  + monthlycharges + totalcharges + tenure , data = cd)
summary(fit)
AIC(fit)
BIC(fit)
```


```{r}
fit <- lm(churn ~ gender + seniorcitizen + partner + dependents + phoneservice + multiplelines + onlinesecurity + internetserviceno +internetserviceDSL +onlinebackup + deviceprotection + techsupport + streamingtv + streamingmovies + contractoneyear + contracttwoyear  + paperlessbilling + paymentmethodelectroniccheck +paymentmethodcreditcard +paymentmethodbanktransfer  + monthlycharges + totalcharges + tenureq1 +tenureq2 +tenureq3 +tenureq3 , data = cd)
summary(fit)
AIC(fit)
BIC(fit)
```

```{r}
fit <- lm(churn ~ gender + seniorcitizen + partner + dependents + phoneservice + multiplelines + onlinesecurity + internetserviceno +internetserviceDSL + onlinebackup + deviceprotection + techsupport + streamingtv + streamingmovies + contractoneyear + contracttwoyear + paperlessbilling + paymentmethodelectroniccheck +paymentmethodmailedcheck+paymentmethodbanktransfer + paymentmethodelectroniccheck+ monthlycharges + totalcharges + tenureshortterm +tenurelongterm , data = cd)
summary(fit)
AIC(fit)
BIC(fit)
```
```{r}
fit <- lm(churn ~ gender + seniorcitizen + partner + dependents + phoneservice + multiplelines + onlinesecurity + internetserviceno +internetserviceDSL + onlinebackup + deviceprotection + techsupport + streamingtv + streamingmovies + contractoneyear + contracttwoyear + paperlessbilling + paymentmethodauto + monthlycharges + totalcharges +tenuremidterm +tenureshortterm, data = cd)
summary(fit)
AIC(fit)
BIC(fit)
```

```{r}
fit <- lm(churn ~ gender + seniorcitizen + partner + dependents + phoneservice + multiplelines + onlinesecurity + internetserviceno +internetserviceDSL +  onlinebackup + deviceprotection + techsupport + streamingtv + streamingmovies + contractoneyear + contracttwoyear + paperlessbilling +paymentmethodcheck  + monthlycharges + totalcharges +tenure, data = cd)
summary(fit)
AIC(fit)
BIC(fit)
```
Highest adjustedR
Lowest AIC
Lowest BIC
```{r}
fit <- lm(churn ~ gender + seniorcitizen + partner + dependents + phoneservice + multiplelines + onlinesecurity + internetserviceno +internetserviceDSL + onlinebackup + deviceprotection + techsupport + streamingtv + streamingmovies + contractoneyear + contracttwoyear  + paperlessbilling + paymentmethodauto  + monthlycharges + totalcharges +tenureq1 +tenureq2 +tenureq3, data = cd)
summary(fit)
AIC(fit)
BIC(fit)
```

lowest pvalue
