---
title: "Data Cleaning"
author: "Paige, Vicky, and Jackie"
date: '2019-11-10'
output: 
  prettydoc::html_pretty:
  theme : cayman
  highlight : github
  math: katex
---

##Libraries
```{r}
library(purrr)
library(dplyr)
library(knitr)
library(forcats)
```

## Load origin data
```{r}
# Load the data
cd1 <- read.csv(file = "Churn.csv", header = TRUE, sep = ",", 
                stringsAsFactors = T)

print("ORIGIN DATA")
summary(cd1)
```

### Clean Data
```{r}

# Edit column names so that they are all lowercase
colnames(cd1) <- map(colnames(cd1), tolower)


# update all factors containing "No internet service" to be part of the "No" level
cd1[10:15] <- lapply(cd1[10:15], function(x) fct_collapse(x, No = c("No", "No internet service")) )



cd1%>%
  # update all factor containing "No phone service" to be part of the "No" level
  mutate(
    multiplelines = fct_collapse(
      multiplelines, No = c("No", "No phone service")
    )
  ) %>%
    # gather factors for payment into two levels, auto deposits and manual checks
    mutate(
      paymentmethodA = fct_collapse(
        paymentmethod, 
        auto = c("bankTransfer", "creditCard"),
        check = c("electronicCheck", "mailedCheck")
      )
    ) %>%
      # gather factors for payments based on electronic or non electronic
      mutate(
        paymentmethodB = fct_collapse(
          paymentmethod, 
          electronic = c("bankTransfer", "creditCard", "electronicCheck"),
          paper = c("mailedCheck")
        )
      ) %>%
        # update customer ID to character 
        mutate(
          customerid = as.character(customerid)
        ) %>%
          # bin tenure into short term, mid range, and long term
          mutate(
            tenure3 = cut(
              tenure, breaks = c(-Inf, 20, 60, Inf), labels = c("shortTerm", "midTerm", "longTerm")
            )
          ) %>%
            # bin tenure into quantiles
            mutate(
              tenure4 = cut(
                tenure, breaks = c(-Inf, 9, 29, 55, Inf), labels = c("q1", "q2", "q3", "q4")
              )
            ) %>%
              # update senior citizen as a factor with levels "Yes" and "No"
              mutate(
                seniorcitizen = as.factor(
                  sapply(
                    seniorcitizen, function (x) ifelse(x == 0, "Yes", "No")
                  )
                )
              )-> cd1


print("TIDIED DATA")    
summary(cd1)
```

#Save data to csv for use in different methodologies

```{r}
write.table(cd1, file = "cleanData.csv",row.names=FALSE, na="",col.names=TRUE, sep=",")
```

