---
title: "Churn analysis with neuralnet"
author: "Paige, Vicky, and Jackie"
date: '2019-11-10'
output: 
  prettydoc::html_pretty:
  theme : cayman
  highlight : github
  math: katex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Info:
```{r}
# Link to the article that informed this code
# https://www.datacamp.com/community/tutorials/neural-network-models-r
```

Example
```{r, eval = F}
#library(neuralnet)
#library(dplyr)

# creating training data set
TKS1 = c(20, 10, 30, 20, 80, 30)
CSS1 = c(90, 20, 40, 50, 50, 80)
Placed1 = c(1, 0, 0, 0, 1, 1)

# Here, you will combine multiple columns or features into a single set of data
df1 = data.frame(TKS1, CSS1, Placed1)

# Fitting the neural network
nn1 <- neuralnet(Placed1 ~ TKS1 + CSS1, data = df1, hidden = 3, act.fct = "logistic", linear.output = F)

# Plotting the neural network
plot(nn1)

# Creating a test set
TKS1 = c(30, 40, 85)
CSS1 = c(85, 50, 40)
test1 <- data.frame(TKS1, CSS1)

# Predict 'Placed1'
Predict1 = neuralnet::compute(nn1, test1)
Predict1$net.result

# Converting probabilities into binary placed or not
prob1 <- Predict1$net.result
(pred1 <- ifelse(prob1 > 0.5, yes = 1, no = 0))
```

**Trying neural networks with churn data**

##Libraries
```{r}
library(neuralnet)
library(purrr)
library(dplyr)
library(knitr)
library(forcats)
library(effects) # For effect plots
```

## Load origin data
```{r}
# Load the data
cd1 <- read.csv(file = "Churn.csv", header = TRUE, sep = ",", 
                stringsAsFactors = T)

print("ORIGIN DATA")
summary(cd1)
```

### Clean Data
```{r}

# Edit column names so that they are all lowercase
colnames(cd1) <- map(colnames(cd1), tolower)


# update all factors containing "No internet service" to be part of the "No" level
cd1[10:15] <- lapply(cd1[10:15], function(x) fct_collapse(x, No = c("No", "No internet service")) )



cd1%>%
  # update all factor containing "No phone service" to be part of the "No" level
  mutate(
    multiplelines = fct_collapse(
      multiplelines, No = c("No", "No phone service")
    )
  ) %>%
    # gather factors for payment into two levels, auto deposits and manual checks
    mutate(
      paymentmethodA = fct_collapse(
        paymentmethod, 
        auto = c("bankTransfer", "creditCard"),
        check = c("electronicCheck", "mailedCheck")
      )
    ) %>%
      # gather factors for payments based on electronic or non electronic
      mutate(
        paymentmethodB = fct_collapse(
          paymentmethod, 
          electronic = c("bankTransfer", "creditCard", "electronicCheck"),
          paper = c("mailedCheck")
        )
      ) %>%
        # update customer ID to character 
        mutate(
          customerid = as.character(customerid)
        ) %>%
          # bin tenure into short term, mid range, and long term
          mutate(
            tenure3 = cut(
              tenure, breaks = c(-Inf, 20, 60, Inf), labels = c("shortTerm", "midTerm", "longTerm")
            )
          ) %>%
            # bin tenure into quantiles
            mutate(
              tenure4 = cut(
                tenure, breaks = c(-Inf, 9, 29, 55, Inf), labels = c("q1", "q2", "q3", "q4")
              )
            ) %>%
              # update senior citizen as a factor with levels "Yes" and "No"
              mutate(
                seniorcitizen = as.factor(
                  sapply(
                    seniorcitizen, function (x) ifelse(x == 0, "Yes", "No")
                  )
                )
              )-> cd1


print("TIDIED DATA")    
summary(cd1)
```

## Fitting the model
```{r}
# Fitting the neural network
full_formula <- as.formula(paste("churn ~ ", paste(colnames(cd1)[c(2:5, 7:17, 19, 22:25)], collapse = " + ")))

# Only using monthlycharges and tenure columns for now
# Using full_formula as the formula gives an error stating that everything has
# to be numeric/vector/something else
nn1 <- neuralnet(churn ~ monthlycharges + tenure, data = cd1, hidden = 3, act.fct = "logistic", linear.output = F)

plot(nn1)
```

## Using effect plots to detemine which regressors to use for logistic reg.
```{r, fig.width = 10, fig.height = 8}
# Making effect plots and omitting certain variables
# Splitting into three plots so that it is more readable
# Create the three formulas
formula_1 <- as.formula(paste("churn ~ ", paste(colnames(cd1)[c(2:5, 7:11)], collapse = " + ")))
formula_2 <- as.formula(paste("churn ~ ", paste(colnames(cd1)[c(12:17, 19, 22, 23)], collapse = " + ")))
formula_3 <- as.formula(paste("churn ~ ", paste(colnames(cd1)[c(24, 25)], collapse = " + ")))
# Creating the logistic regression models
lrfit1 <- glm(formula_1, cd1, family = binomial(link = "logit"))
lrfit2 <- glm(formula_2, cd1, family = binomial(link = "logit"))
lrfit3 <- glm(formula_3, cd1, family = binomial(link = "logit"))
# Making the plots; third plot is in the next code chunk
plot(allEffects(lrfit1), type = "response")
plot(allEffects(lrfit2), type = "response")
#plot(allEffects(lrfit3), type = "response")
```

```{r, fig.width = 8, fig.height = 4}
plot(allEffects(lrfit3), type = "response")
```






