---
title: "Variable Selection linear model"
author: "PaigeT"
date: "24/11/2019"
output: html_document
---

---
title: "Variable Selection"
author: "Paige, Vicky, and Jackie"
date: '2019-11-10'
output: 
  prettydoc::html_pretty:
  theme : cayman
  highlight : github
  math: katex
---

#selection methods to determine best regressors


```{r}
library(ggplot2)
library(leaps)
library(knitr)
```

#load data

```{r}
library(dplyr)# Load the data
cd <- read.csv(file = "oneHotClean.csv", header = TRUE, sep = ",", 
                stringsAsFactors = T)

print("ORIGIN DATA")

summary(cd)
```


```{r}
mod = regsubsets(
  churn ~ gender + seniorcitizen + partner + dependents + phoneservice + multiplelines + onlinesecurity + internetserviceno +internetserviceDSL +  onlinebackup + deviceprotection + techsupport + streamingtv + streamingmovies + contractoneyear + contracttwoyear + paperlessbilling +paymentmethodcheck  + monthlycharges + totalcharges +tenure, data = cd,nbest = 10)

mod.summary = summary(mod)

which.max(mod.summary$adjr2)
which.min(mod.summary$cp)
which.min(mod.summary$bic)

coef(mod, id = 41)
coef(mod, id = 21)
coef(mod, id = 11)

print("ADJR, CP, BIC")
print("5 regressor model")
print(mod.summary$adjr2[41])
print(mod.summary$cp[41])
print(mod.summary$bic[41])
print("3 regressor model")
print(mod.summary$adjr2[21])
print(mod.summary$cp[21])
print(mod.summary$bic[21])
print("2 regressor model")
print(mod.summary$adjr2[11])
print(mod.summary$cp[11])
print(mod.summary$bic[11])
```

```{r}
fit  = lm(
    churn ~ 
      internetserviceno +
      internetserviceDSL +
      paymentmethodcheck,
  data = cd
)
summary(fit)
print("AIC")
AIC(fit)
print("BIC")
BIC(fit)
```



# try selection

```{r}
library(MASS)
library(stats4)

mfit_null  = lm(churn~1, data=cd)
mfit_full  = lm( churn ~ gender + seniorcitizen + partner + dependents + phoneservice + multiplelines + onlinesecurity + internetserviceno +internetserviceDSL +  onlinebackup + deviceprotection + techsupport + streamingtv + streamingmovies + contractoneyear + contracttwoyear + paperlessbilling +paymentmethodcheck  + monthlycharges + totalcharges +tenure, data = cd)
step <- step(mfit_null, data=cd, scope=list(upper=mfit_full), direction="both")
step
BIC(step)
```


