---
title: "Variable Selection"
author: "Paige, Vicky, and Jackie"
date: '2019-11-10'
output: 
  prettydoc::html_pretty:
  theme : cayman
  highlight : github
  math: katex
---

#selection methods to determine best regressors


```{r}
library(ggplot2)
library(leaps)
library(knitr)
```

#load data

```{r}
library(dplyr)# Load the data
cd <- read.csv(file = "cleanData.csv", header = TRUE, sep = ",", 
                stringsAsFactors = T)

print("ORIGIN DATA")

summary(cd)
```


```{r}
mod = regsubsets(
  churn ~ 
    gender  +
    seniorcitizen +
    dependents +
    partner +
    phoneservice +
    multiplelines +
    internetservice +
    onlinebackup +
    onlinesecurity +
    deviceprotection +
    techsupport +
    streamingtv +
    streamingmovies +
    contract +
    paperlessbilling +
    monthlycharges +
    totalcharges +
    paymentmethod +
    tenure4, 
  data = cd,
  nbest = 10
)
mod.summary = summary(mod)

which.max(mod.summary$adjr2)
which.min(mod.summary$cp)
which.min(mod.summary$bic)

coef(mod, id = 71)

print(mod.summary$adjr2[71])
print(mod.summary$cp[71])
print(mod.summary$bic[71])
```

tied for highest adjr

```{r}
mod = regsubsets(
  churn ~ 
    gender  +
    seniorcitizen +
    dependents +
    partner +
    phoneservice +
    multiplelines +
    internetservice +
    onlinebackup +
    onlinesecurity +
    deviceprotection +
    techsupport +
    streamingtv +
    streamingmovies +
    contract +
    paperlessbilling +
    monthlycharges +
    totalcharges +
    paymentmethod +
    tenure3, 
  data = cd,
  nbest = 10
)
mod.summary = summary(mod)

which.max(mod.summary$adjr2)
which.min(mod.summary$cp)
which.min(mod.summary$bic)

coef(mod, id = 71)
print(mod.summary$adjr2[71])
print(mod.summary$cp[71])
print(mod.summary$bic[71])
```


```{r}
mod = regsubsets(
  churn ~ 
    gender  +
    seniorcitizen +
    dependents +
    partner +
    tenure +
    phoneservice +
    multiplelines +
    internetservice +
    onlinebackup +
    onlinesecurity +
    deviceprotection +
    techsupport +
    streamingtv +
    streamingmovies +
    contract +
    paperlessbilling +
    monthlycharges +
    totalcharges +
    paymentmethod,
  data = cd,
  nbest = 10
)
mod.summary = summary(mod)

which.max(mod.summary$adjr2)
which.min(mod.summary$cp)
which.min(mod.summary$bic)

coef(mod, id = 71)
print(mod.summary$adjr2[71])
print(mod.summary$cp[71])
print(mod.summary$bic[71])
```

this one has the lowest cp mallow

```{r}
fit <- glm(
  churn ~
    phoneservice + 
    onlinesecurity +
    techsupport +
    contract +
    monthlycharges + 
    totalcharges +
    paymentmethod,
  data = cd, 
  family = "binomial"
)
summary(fit)
BIC(fit)
```


```{r}
mod = regsubsets(
  churn ~ 
    gender  +
    seniorcitizen +
    dependents +
    partner +
    phoneservice +
    multiplelines +
    internetservice +
    onlinebackup +
    onlinesecurity +
    deviceprotection +
    techsupport +
    streamingtv +
    streamingmovies +
    contract +
    paperlessbilling +
    monthlycharges +
    totalcharges +
    paymentmethodAuto +
    tenure3, 
  data = cd,
  nbest = 10
)
mod.summary = summary(mod)

which.max(mod.summary$adjr2)
which.min(mod.summary$cp)
which.min(mod.summary$bic)

coef(mod, id = 71)
print(mod.summary$adjr2[71])
print(mod.summary$cp[71])
print(mod.summary$bic[71])
```



```{r}
mod = regsubsets(
  churn ~ 
    gender  +
    seniorcitizen +
    dependents +
    partner +
    phoneservice +
    multiplelines +
    internetservice +
    onlinebackup +
    onlinesecurity +
    deviceprotection +
    techsupport +
    streamingtv +
    streamingmovies +
    contract +
    paperlessbilling +
    monthlycharges +
    totalcharges +
    paymentmethodAuto +
    tenure4, 
  data = cd,
  nbest = 10
)
mod.summary = summary(mod)

which.max(mod.summary$adjr2)
which.min(mod.summary$cp)
which.min(mod.summary$bic)

coef(mod, id = 71)
print(mod.summary$adjr2[71])
print(mod.summary$cp[71])
print(mod.summary$bic[71])
```

This one has the lowest bic
tied for highest adjr

```{r}
fit <- glm(
  churn ~
    phoneservice + 
    onlinesecurity +
    techsupport +
    contract +
    monthlycharges + 
    totalcharges +
    tenure4,
  data = cd, 
  family = "binomial"
)
summary(fit)
BIC(fit)
```


```{r}
mod = regsubsets(
  churn ~ 
    gender  +
    seniorcitizen +
    dependents +
    partner +
    tenure +
    phoneservice +
    multiplelines +
    internetservice +
    onlinebackup +
    onlinesecurity +
    deviceprotection +
    techsupport +
    streamingtv +
    streamingmovies +
    contract +
    paperlessbilling +
    monthlycharges +
    totalcharges +
    paymentmethodAuto,
  data = cd,
  nbest = 10
)
mod.summary = summary(mod)

which.max(mod.summary$adjr2)
which.min(mod.summary$cp)
which.min(mod.summary$bic)

coef(mod, id = 71)
print(mod.summary$adjr2[71])
print(mod.summary$cp[71])
print(mod.summary$bic[71])
```

# try selection

```{r}
library(MASS)
library(stats4)

mfit_null  = glm(churn~1, data=cd, family = "binomial")
mfit_full  = glm(
    churn ~ 
    gender  +
    seniorcitizen +
    dependents +
    partner +
    phoneservice +
    multiplelines +
    internetservice +
    onlinebackup +
    onlinesecurity +
    deviceprotection +
    techsupport +
    streamingtv +
    streamingmovies +
    contract +
    paperlessbilling +
    monthlycharges +
    totalcharges +
    paymentmethodAuto +
    tenure4, 
  data = cd,
  family = "binomial"
)
step <- step(mfit_null, data=cd, scope=list(upper=mfit_full), direction="both")
step
BIC(step)
```

```{r}
mfit_null  = glm(churn~1, data=cd, family = "binomial")
mfit_full  = glm(
    churn ~ 
    gender  +
    seniorcitizen +
    dependents +
    partner +
    phoneservice +
    multiplelines +
    internetservice +
    onlinebackup +
    onlinesecurity +
    deviceprotection +
    techsupport +
    streamingtv +
    streamingmovies +
    contract +
    paperlessbilling +
    monthlycharges +
    totalcharges +
    paymentmethodAuto +
    tenure3, 
  data = cd,
  family = "binomial"
)
step <- step(mfit_null, data=cd, scope=list(upper=mfit_full), direction="both")
step
BIC(step)
```

```{r}
mfit_null  = glm(churn~1, data=cd, family = "binomial")
mfit_full  = glm(
    churn ~ 
    gender  +
    seniorcitizen +
    dependents +
    partner +
    phoneservice +
    multiplelines +
    internetservice +
    onlinebackup +
    onlinesecurity +
    deviceprotection +
    techsupport +
    streamingtv +
    streamingmovies +
    contract +
    paperlessbilling +
    monthlycharges +
    totalcharges +
    paymentmethodAuto +
    tenure, 
  data = cd,
  family = "binomial"
)
step <- step(mfit_null, data=cd, scope=list(upper=mfit_full), direction="both")
step
BIC(step)
```
Lowest BIC
```{r}
mfit_null  = glm(churn~1, data=cd, family = "binomial")
mfit_full  = glm(
    churn ~ 
    gender  +
    seniorcitizen +
    dependents +
    partner +
    phoneservice +
    multiplelines +
    internetservice +
    onlinebackup +
    onlinesecurity +
    deviceprotection +
    techsupport +
    streamingtv +
    streamingmovies +
    contract +
    paperlessbilling +
    monthlycharges +
    totalcharges +
    paymentmethod +
    tenure4, 
  data = cd,
  family = "binomial"
)
step <- step(mfit_null, data=cd, scope=list(upper=mfit_full), direction="both")
step
BIC(step)
```

```{r}
mfit_null  = glm(churn~1, data=cd, family = "binomial")
mfit_full  = glm(
    churn ~ 
    gender  +
    seniorcitizen +
    dependents +
    partner +
    phoneservice +
    multiplelines +
    internetservice +
    onlinebackup +
    onlinesecurity +
    deviceprotection +
    techsupport +
    streamingtv +
    streamingmovies +
    contract +
    paperlessbilling +
    monthlycharges +
    totalcharges +
    paymentmethod +
    tenure, 
  data = cd,
  family = "binomial"
)
step <- step(mfit_null, data=cd, scope=list(upper=mfit_full), direction="both")
step
BIC(step)
```
lowest AIC

```{r}
mfit_null  = glm(churn~1, data=cd, family = "binomial")
mfit_full  = glm(
    churn ~ 
    gender  +
    seniorcitizen +
    dependents +
    partner +
    phoneservice +
    multiplelines +
    internetservice +
    onlinebackup +
    onlinesecurity +
    deviceprotection +
    techsupport +
    streamingtv +
    streamingmovies +
    contract +
    paperlessbilling +
    monthlycharges +
    totalcharges +
    paymentmethod +
    tenure3, 
  data = cd,
  family = "binomial"
)
step <- step(mfit_null, data=cd, scope=list(upper=mfit_full), direction="both")
step
BIC(step)
```

Trying glmnet
```{r}
library(glmnet)

ma1 <- model.matrix(object = churn ~ ., data = cd)
glmnet(ma1, as.numeric(cd$churn) - 1)
```

